version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-vsrx"
s3_bucket = "<your-s3-bucket-for-SAM-cli>"
s3_prefix = "test-vsrx"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AvailabilityZone1=\"eu-west-1a\" AvailabilityZone2=\"eu-west-1b\" AvailabilityZone3=\"eu-west-1c\" KeyPair=\"TestNetwork\" PublicSSHAccess=\"true\" JumpHostIPrange=\"0.0.0.0/0\" SnsEmail=\"foo@foo.bar\" LambdaInfoTracing=\"true\" ASGCoolDownTime=\"10\" ASGHealthCheckGracePeriod=\"600\" ASGUpdateHealthCheckGraceTime=\"120\" SubnetCreationAttempts=\"10\" VPCCIDRBlock=\"10.16.0.0/16\" WAN1SubnetCIDRBlock=\"10.16.1.0/24\" WAN2SubnetCIDRBlock=\"10.16.2.0/24\" WAN3SubnetCIDRBlock=\"10.16.3.0/24\" VIPCIDRBlock=\"10.16.10.0/24\" VIPAddress=\"10.16.10.20/32\" InstanceChoice=\"JunipervSRX\" InstanceType=\"c5.large\" InstanceRequiresReboot=\"true\" CustomAmiId=\"/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2\" CustomUserData=\"\""
image_repositories = []
